global using Order.Domain.Models;
global using OrderEntity = Order.Domain.Models.Order;
global using Order.Domain.ValueObjects;
global using BuildingBlocks.CQRS;
global using Order.Application.Data;
global using Order.Application.Dtos;
global using Order.Application.Exceptions;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using Order.Domain.Events;
global using Microsoft.EntityFrameworkCore;
global using Order.Application.Extensions;