services:
  inventorydb: 
    image: postgres

  identityserverdb:
    image: mcr.microsoft.com/mssql/server

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Services/Inventory/Inventory.API/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Identity/IdentityServer/Dockerfile

volumes:
   postgres_inventory:
