services:
  inventorydb:
    container_name: inventorydb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=InventoryDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_inventory:/var/lib/postgresql/data/
    networks:
      - mynetwork

  identityserverdb:
    container_name: identityserverdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin12345678!
    restart: always
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  inventory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=inventorydb;Port=5432;Database=InventoryDb;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - inventorydb
      - identityserver
    volumes:
      - C:\Users\User\Documents\NetProjects\duranx\Certificates:/app/certificates
    networks:
      - mynetwork

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=identityserverdb;Database=aspnet-IdentityServer;User Id=sa;Password=Admin12345678!;Encrypt=False;TrustServerCertificate=True
    ports:
      - "6006:8080"
      - "6066:8081"
    depends_on:
      - identityserverdb
    volumes:
      - C:\Users\User\Documents\NetProjects\duranx\Certificates:/app/certificates
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
