version: '3.4'

services:
  inventorydb:
    container_name: inventorydb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=InventoryDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_inventory:/var/lib/postgresql/data/

  cartdb:
    container_name: cartdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CartDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_cart:/var/lib/postgresql/data/ 

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
      
  inventory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=inventorydb;Port=5432;Database=InventoryDb;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - inventorydb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
