services:
  cartdb:
    image: postgres

  rabbitmq:
    image: rabbitmq:management
  
  webapi:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.API/Dockerfile

volumes:
   postgres_cart:
    