services:
  cartdb:
    container_name: cartdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CartDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_cart:/var/lib/postgresql/data/ 
    networks:
      - mynetwork

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
       - "5671:5671"
       - "15672:15672"
    volumes:
      - C:\Users\User\Documents\NetProjects\duranx\RabbitMQ\Log:/var/log/rabbitmq
      - C:\Users\User\Documents\NetProjects\duranx\Certificates:/etc/rabbitmq/ssl
      - C:\Users\User\Documents\NetProjects\duranx\RabbitMQ\rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - mynetwork
    command: rabbitmq-server --ssl

  webapi:
    environment:
      - aspnetcore_environment=development
      - aspnetcore_http_ports=8080
      - aspnetcore_https_ports=8081
      - connectionstrings__database=server=cartdb;port=5432;database=cartdb;user id=postgres;password=postgres;include error detail=true
      - messagebroker__host=amqps://rabbitmq:5671
      - messagebroker__username=guest
      - messagebroker__password=guest
      - messagebroker__certificate__path=/usr/local/share/ca-certificates/webapi.p12
      - messagebroker__certificate__password=duranxpassword
      - rabbitmq__hostname=rabbitmq
      - rabbitmq__servername=rabbitmq
      - rabbitmq__certpath=/usr/local/share/ca-certificates/webapi.p12
      - rabbitmq__certpassphrase=duranxpassword
      - rabbitmq__username=guest
      - rabbitmq__password=guest
    ports:
      - "6001:8080"
      - "6061:8081"
    depends_on:
      - rabbitmq
    volumes:
      - c:\users\user\documents\netprojects\duranx\certificates:/app/certificates
      - ${appdata}/microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${appdata}/asp.net/https:/home/app/.aspnet/https:ro
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
